// prettier.config.js
module.exports = {
  arrowParens: 'always',
  endOfLine: 'auto',
  semi: false,
  singleQuote: true,
  trailingComma: 'all',
  // bracketSpacing: true,
  // htmlWhitespaceSensitivity: 'css',
  // insertPragma: false,
  // singleAttributePerLine: false,
  // bracketSameLine: false,
  // jsxBracketSameLine: false,
  // jsxSingleQuote: false,
  // printWidth: 80,
  // proseWrap: 'preserve',
  // quoteProps: 'as-needed',
  // requirePragma: false,
  // tabWidth: 2,
  // useTabs: false,
  // embeddedLanguageFormatting: 'auto',
  // vueIndentScriptAndStyle: false,
}
