import type { FoodItemProps } from './nutritionIntake.js'

export const dailyFoodIntakeCurrent: FoodItemProps = {
  rice: {
    calories: 355,
    carbohydrates: 79,
    protein: 7.3,
    sugar: 0.3,
    fat: 0.2,
    per100Grams: true,
    quantity: 120,
    frequency: 2,
  },
  fish: {
    calories: 181,
    carbohydrates: 15,
    protein: 14,
    sugar: 0.6,
    fat: 0.5,
    per100Grams: false,
    quantity: 5,
    frequency: 2,
  },
  chicken: {
    calories: 98,
    carbohydrates: 1.2,
    protein: 20,
    sugar: 0,
    fat: 0,
    per100Grams: true,
    quantity: 120,
    frequency: 2,
  },
  'white-bread': {
    calories: 109,
    carbohydrates: 17,
    protein: 3.9,
    sugar: 0,
    fat: 0,
    per100Grams: false,
    quantity: 2,
    frequency: 2,
  },
  fromageblanc: {
    calories: 100,
    carbohydrates: 0,
    protein: 7.3,
    sugar: 0,
    fat: 0,
    per100Grams: false,
    quantity: 2,
    frequency: 2,
  },
}

export const dailyFoodIntakeAdjusted: FoodItemProps = {
  rice: {
    calories: 355,
    carbohydrates: 79,
    protein: 7.3,
    sugar: 0.3,
    fat: 0.2,
    per100Grams: true,
    quantity: 95,
    frequency: 2,
  },
  spaghetti: {
    calories: 361,
    carbohydrates: 72,
    protein: 12,
    sugar: 3.7,
    fat: 0.35,
    per100Grams: true,
    quantity: 120,
    frequency: 0,
  },
  'fried-fish': {
    calories: 181,
    carbohydrates: 15,
    protein: 14,
    sugar: 0.6,
    fat: 0.5,
    per100Grams: false,
    quantity: [4, 4],
    frequency: 1,
  },
  'fresh-pizza': {
    calories: 247,
    carbohydrates: 26.8,
    protein: 12.2,
    sugar: 3.5,
    fat: 5.9,
    per100Grams: true,
    quantity: 470,
    frequency: 0,
  },
  'poisson-bordelais': {
    calories: 147,
    carbohydrates: 5.7,
    protein: 14,
    sugar: 0.6,
    fat: 1.7,
    per100Grams: true,
    quantity: 200,
    frequency: 0,
  },
  'filet-colin': {
    calories: 76,
    carbohydrates: 0,
    protein: 17,
    sugar: 0,
    fat: 0.2,
    per100Grams: true,
    quantity: 120,
    frequency: 0,
  },
  'brochettes-boeuf': {
    calories: 150,
    carbohydrates: 15,
    protein: 20,
    sugar: 0,
    fat: 0,
    per100Grams: true,
    quantity: 200,
    frequency: 0,
  },
  'steak-hache-charal': {
    calories: 125,
    carbohydrates: 0,
    protein: 20,
    sugar: 0,
    fat: 0,
    per100Grams: true,
    quantity: 100,
    frequency: 0,
  },
  maquereaux: {
    calories: 238,
    carbohydrates: 0,
    protein: 19,
    sugar: 0,
    fat: 4.1,
    per100Grams: true,
    quantity: 95,
    frequency: 0,
  },
  chicken: {
    calories: 98,
    carbohydrates: 1.2,
    protein: 20,
    sugar: 0,
    fat: 0.4,
    per100Grams: true,
    quantity: 40,
    frequency: 3,
  },
  'white-bread': {
    calories: 109,
    carbohydrates: 17,
    protein: 3.9,
    sugar: 4.4,
    fat: 0.7,
    per100Grams: false,
    quantity: [2],
    frequency: 1,
  },
  'fromage-blanc': {
    calories: 100,
    carbohydrates: 11,
    protein: 7.3,
    sugar: 11,
    fat: 2,
    per100Grams: false,
    quantity: 2,
    frequency: 0,
  },
  'petit-fromage-blanc': {
    calories: 110,
    carbohydrates: 12,
    protein: 7.9,
    sugar: 12,
    fat: 3.4,
    per100Grams: true,
    quantity: 60,
    frequency: 0,
  },
  'yoghourt-vanilla': {
    calories: 95,
    carbohydrates: 13.1,
    protein: 3,
    sugar: 13.1,
    fat: 2,
    per100Grams: true,
    quantity: 125,
    frequency: 0,
  },
  'magnum-amande': {
    calories: 270,
    carbohydrates: 25,
    protein: 3.9,
    sugar: 23,
    fat: 10,
    per100Grams: false,
    quantity: 1,
    frequency: 0,
  },
  sugar: {
    calories: 387,
    carbohydrates: 386.92,
    protein: 0,
    sugar: 386.65,
    fat: 0,
    per100Grams: true,
    quantity: 1,
    frequency: 3,
  },
  egg: {
    calories: 70,
    carbohydrates: 0.27,
    protein: 6.3,
    sugar: 0,
    fat: 0,
    per100Grams: false,
    quantity: 4,
    frequency: 0,
  },
}
